name: deploy
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            REPO_URL=${{ github.server_url }}/${{ github.repository }}.git
            mkdir -p /opt/hyper-facilitator
            cd /opt/hyper-facilitator
            if [ ! -d .git ]; then
              git clone "$REPO_URL" .
            else
              git fetch origin
            fi
            git checkout -f main
            git reset --hard origin/main
            cd Hyper-x402
            cp .env.example .env || true
            docker compose up -d

